const BASE = 'http://localhost:8799', KN = 'http://127.0.0.1:8798';
const ck = async (u, p) => (await fetch(BASE + '/login', { method: 'POST', body: new URLSearchParams({ username: u, password: p }), redirect: 'manual' })).headers.get('set-cookie').split(';')[0];
const call = async (c, m, u, b) => { const r = await fetch(BASE + u, { method: m, headers: { cookie: c, 'content-type': 'application/json', origin: BASE }, body: b ? JSON.stringify(b) : undefined }); return { status: r.status, body: await r.json().catch(() => ({})) }; };
const owner = await ck('owner', 'test');
for (const u of ['cleo', 'maria']) await call(owner, 'POST', '/api/users', { name: u, username: u, password: 'testpass1', role: 'cleaner', buildings: 'all', email: '' });
const [cleo, maria] = [await ck('cleo', 'testpass1'), await ck('maria', 'testpass1')];
await call(owner, 'PUT', '/api/keynest/links', { confirmed: true, changes: [{ listingId: 'm5', keyId: 'K100' }] });
const c = (await call(cleo, 'POST', '/api/cleanings/start', { listingId: 'm5' })).body.cleaning.id;
await call(cleo, 'POST', `/api/cleanings/${c}/end`);
for (const k of ['bins', 'fridge', 'oven', 'microwave', 'hairs']) await call(cleo, 'POST', `/api/cleanings/${c}/confirm`, { key: k });
await call(cleo, 'POST', `/api/cleanings/${c}/checks-done`, { heldMs: 3100 });
const buf = Buffer.alloc(100000, 7);
const s = (await call(cleo, 'POST', '/api/media', { kind: 'video', purpose: 'cleaning', ownerId: c, name: 'v.mov', size: buf.length, type: 'video/quicktime' })).body;
await fetch(`${BASE}/api/media/${s.id}?offset=0`, { method: 'PUT', headers: { cookie: cleo, 'content-type': 'application/octet-stream', origin: BASE }, body: buf });
await call(cleo, 'POST', `/api/cleanings/${c}/complete`, { videoIds: [s.id] });
await fetch(`${KN}/set?status=In+Store&delay=2500`);
const slow = call(cleo, 'POST', `/api/cleanings/${c}/key`, {});
await new Promise((r) => setTimeout(r, 400));
const other = (await call(maria, 'POST', '/api/cleanings/start', { listingId: 'm7' })).body.cleaning.id;
await slow; await fetch(`${KN}/set?delay=0`);
const still = await call(maria, 'GET', `/api/cleanings/${other}`);
console.log(still.status === 200 ? 'KEPT: Maria’s cleaning survived' : 'LOST: Maria’s cleaning was wiped by the slow KeyNest step');
